version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - NEXTAUTH_SECRET=a-very-secret-and-long-string-for-development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - GOOGLE_CLIENT_ID= # User needs to provide this
      - GOOGLE_CLIENT_SECRET= # User needs to provide this
      - GROQ_API_KEY= # User needs to provide this
      - STRIPE_API_KEY= # User needs to provide this
      - STRIPE_WEBHOOK_SECRET= # User needs to provide this
      - STRIPE_PRO_PRICE_ID= # User needs to provide this

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
